//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string Tanda { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Estado { get; set; }
        public string Contrasena { get; set; }
    }
}
